### ISSUE TITLE
An icon has disappeared

### ISSUE THREAD

**Issue by KratorD** [zikula-modules/Ratings#22]
Setting:
Rating scale: 5
Icon fa: fa-star
Half icon fa: fa-star-half-o
Empty icon fa: fa-star-o

_Step-to-step_
1. Rating an element (fe: 3/5)
2. Rating same element (with another user) (fe: 4/5)
3.a The icon was not refresh (3.5 stars)
3.b Reload the page. Only 4 start is showed in the rating. 
![imagen](https://user-images.githubusercontent.com/5812569/81208782-e028e480-8fcf-11ea-8274-7e77c4b5704b.png)

Thanks.

**Comment by paustian** [comment]
Fixed and a new release v3.0.0-a2 released.
